config/routes.rb
Rails.application.routes.draw do

  get 'job_propositions/index'

  get 'job_propositions/new'

  get 'job_propositions/create'

  get 'job_propositions/show'

  get 'job_propositions/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
 
  
    post 'nous-contacter/envoye', to: "requete_generales#create", as: "requete_generales"
    get 'nous-contacter/confirmation', to: "requete_generales#confirm",as: "general_request_confirmation"
    get 'nous-contacter', to: 'requete_generales#new', as: 'contact'

    
    get 'candidat/nouvelle_candidature', to: 'requete_candidats#new', as: 'new_candidate_request'
    post 'candidat/nouvelle_candidature/sauvegarde', to: 'requete_candidats#create', as: 'requete_candidats'
    get 'candidat/confirmation_candidature', to:'requete_candidats#confirm', as: "candidate_request_confirmation" 

    get 'employeur/nouvelle_offre', to: "job_propositions#new", as: 'new_job_proposition'
    post 'employeur/nouvelle_offre/sauvegarder', to: "job_propositions#create", as: 'job_propositions'
    get 'employeur/nouvelle_offre/confirmation', to: "job_propositions#confirm", as: 'job_proposition_confirmation'

    get 'derniere_offres', to: "job_propositions#index", as: "offers"

    
    get 'pages/home'

  
    root 'pages#home'

end

app/models/job_proposition.rb
class JobProposition < ActiveRecord::Base
	
	validates :nom, :telephone, :title, :description, :ville, :quartier, :duree_contrat, :salaire, :principale_taches,
			  presence: true

	def self.ville
		%w(Douala Yaounde)
	end

	def self.salary
		%w(40000-60000 60000-80000 80000-100000 100000+)
	end

	def self.type
		%w(Menagere Nounou Mix)
	end

	def self.jour
		%w(Lundi-Vendredi Lundi-Samedi Lundi-Dimanche Autres )
	end

	
end

app/models/requete_candidat.rb
class RequeteCandidat < ActiveRecord::Base

	validates :nom, :telephone, :prenom, :ville, :quartier, 
			  presence: true
end

app/models/requete_generale.rb
class RequeteGenerale < ActiveRecord::Base
	validates :nom, :telephone, :email, :message, 
			  presence: true
end

app/models/talent.rb
class Talent < ActiveRecord::Base
	belongs_to :talent_information
	belongs_to :talent_identification_information
	mount_uploader :image, AvatarUploader
end

app/models/talent_identification_information.rb
class TalentIdentificationInformation < ActiveRecord::Base
	has_one :talent
	mount_uploader :cni_scan, CniUploader
end

app/models/talent_information.rb
class TalentInformation < ActiveRecord::Base
	has_one :talent
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :admin, lambda { where(admin: true) }
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_propositions_controller.rb
class JobPropositionsController < ApplicationController
  def index
     @jobs = JobProposition.last(5)
     @meta_description = "Vous recherchez une menagere, nounou? Alors postez votre offre? Vous etes une menagere a la recherche d'un boulot? Enregistrez vous pour postuler."
  end

  def new
     @job = JobProposition.new
     @meta_description = "A la recherche d'une menagere ou une nounou? postez votre besoin et nous reviendrons vers vous dans de bref delais. Phone:+237 683867665"
  end

  def create
    session[:previous_path_valid] = true
    @job = JobProposition.new(job_params)
    if @job.save
      redirect_to job_proposition_confirmation_path
    else
      render 'new', danger: "Verifier le formulaire et re-essayer"
    end
  end

  def show
  end

  def confirm
    if session[:previous_path_valid]
      session[:previous_path_valid] = false
      @meta_description = "Merci de faire appel a nous. Nous disposons de menageres et de nounous formees, qualifiees et experimentees alors restez confiant. Phone:+237 683867665"
      render 'confirm'   
    else
      redirect_to new_job_proposition_path
    end
  end

  def destroy
  end

  private

  def job_params  
    params[:job_proposition].permit(:title, :description, :ville, :quartier, :duree_contrat, :status_emmenagement,:principale_taches,
      :salaire, :jour_travail, :heure_travail_debut, :heure_travail_fin)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@meta_description = "C'est enfin possible, une menagere ou nounou qualifiee pour votre domicile en moins de 48h dans les ville de Yaounde et Douala"
  end

  def contact
  	@meta_description = "Nous disposons de menageres et de nounous formees, qualifiees et experimentees alors appellez nous au 683867665 pour un service rapide"
  end
end

app/controllers/requete_candidats_controller.rb
class RequeteCandidatsController < ApplicationController
  def new
  	@request = RequeteCandidat.new
     @meta_description = "Vous etes une menagere ou une nounou a la recherche d'un boulot a Yaounde / Douala? Rejoignez notre grande famille et trouvez des opportunitees. call:683867665"
  end

  def create
  	@request = RequeteCandidat.new(request_params)
    session[:previous_path_valid] = true
  	if @request.save
  		redirect_to candidate_request_confirmation_path
  	else
  		render 'new'
  	end
  end

  def confirm
     if session[:previous_path_valid]
      session[:previous_path_valid] = false
      @meta_description = "Nous avons constamment besoins des profils comme le votre, alors restez confiant, Nous reviendrons vers vous dans de bref delais"
      render 'confirm'   
    else
      redirect_to new_candidate_request_path
    end
  end

  private

  def request_params
  	params[:requete_candidat].permit(:nom, :prenom, :ville, :quartier, :telephone, :email, :experience)
  end
end

app/controllers/requete_generales_controller.rb
class RequeteGeneralesController < ApplicationController
   def new
  	@request = RequeteGenerale.new
    @meta_description = "Nous disposons de menageres et de nounous formees, qualifiees et experimentees alors appellez nous au 683867665 pour un service rapide"
  end

  def create
  	@request = RequeteGenerale.new(request_params)
    session[:previous_path_valid] = true

  	if @request.save
  		redirect_to general_request_confirmation_path
  	else
  		render 'new'
  	end
  end

  def confirm
    if session[:previous_path_valid]
      session[:previous_path_valid] = false
      @meta_description = "Nous disposons de menageres et de nounous formees, qualifiees et experimentees. Nous reviendrons vers vous dans de bref delais"
      render 'confirm'   
    else
      redirect_to contact_path
    end
  end

  private

  def request_params
  	params[:requete_generale].permit(:nom, :prenom,  :telephone, :email, :sujet, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/job_propositions_helper.rb
module JobPropositionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requete_candidats_helper.rb
module RequeteCandidatsHelper
end

app/helpers/requete_generales_helper.rb
module RequeteGeneralesHelper
end

app/views/job_propositions/confirm.html.erb
<section id="page-head">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">		
				<h2>Rejoignez Nous</h2>
				<p>
				Nous sommes perpetuellement a la recherche de femmes(filles) dynamique dans l'optique d'agrandir notre reseaux. Alors nous sommes honores que vous souhaitiez devenir membre de notre grande famille, Merci nous reviendrons vers vous.
				</p>
			</div>
		</div>
	</div>	
</section>

<br>
<br>

<div class="container">
	<div class="row">
		<div class="alert alert-success">
			<strong>Enregistrement Recu</strong><br />
			Votre offre a ete enregistree avec success. Apres validation par un administrateur nous vous contacterons et votre offre sera publiee sur notre page. Merci de continuer a nous faire confiance
		</div>	
	</div>
</div>

<br>
<br>

<div class="container">
	<div class="row text-center">
		<div class="btn btn-lg btn-dark ">Voir la liste de job</div> ou
		<%= link_to "Retourner a l'accueil", root_path, class: "btn btn-lg btn-dark" %>
	</div>
</div>

<br>
<br>

app/views/job_propositions/index.html.erb
<section id="page-head">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">		
				<h2>Nos Derniere Offres</h2>
				<p>
					Ici ne sont disponible que les dernieres offres publie sur notre site, nous disposons de beaucoup plus... Alors si l'une des offres listees vous interesses ou si vous desirez poster une offre  , alors n'hesitez pas a nous contacter ou nous appeller au <a style="color: white;" href="tel:+237694840049">6 94 84 00 49</a>
				</p>
			</div>
		</div>
	</div>	
</section>


<section id="offers">
  
	

	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">

				<% if @jobs.blank? %>
					<p class="no-jobs">
						Rien ici pour l'instant
					</p>
				<% end -%>

				<% @jobs.reverse.each do |job| %>

					<div class="panel panel-default offer">
						<div class="panel-heading">
							publie <%= time_ago_in_words job.created_at %> <span class="pull-right">par <%= job.nom %></span>
						</div>
						<div class="panel-body">
							<h5 class="heading"><%= job.title %><span class="left"></span></h5>
							<p>
								<%= job.description %>
							</p>	
							<hr>
							<div class="table-responsive">
								<table class="table table-bordered">
									<tr>
										<td><strong>Taches : </strong></td>
										<td colspan="5">
											<% job.principale_taches.split(',').each do |tache|  %>
												<span class="badge "><%= tache  %></span>
											<% end -%>
										</td>
									</tr>
									<tr>
										<td><strong>Salaire :</strong></td>
										<td><%= job.salaire %></td>
										<td><strong>Ville :</strong></td>
										<td><%= job.ville %></td>
										<td><strong>Quartier :</strong></td>
										<td><%= job.quartier %></td>
									</tr>
								</table>
							</div>
						</div>
					</div>

				<% end -%>


			</div>
		</div>
	</div>
</section>

<section id="bottom">
	<div class="container-fluid">
		<div class="row">

			<div class="division1">
				<p>Vous desirez poster une offre d'emplois</p>
				<%= link_to "Creer une offre", new_job_proposition_path, class: "btn btn-lg btn-red "  %>
			</div>
			<div class="division2">
				<p>Vous desirez postuler a une offre</p>
				<%= link_to "Postuler", new_candidate_request_path, class: "btn btn-lg btn-red"  %>
			</div>

		</div>
	</div>
</section>

app/views/job_propositions/new.html.erb
<section id="page-head">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">		
				<h2>Pour Employeur</h2>
				<p>
				Vous faciliter la vie lors de vos recherches d'employes (menageres / babysitters) pour votre domicile est notre raison d'etre, alors restez confiant car nous ferons le necessaire pour votre satisfaction.
			</div>
		</div>
	</div>	
</section>

<section class="lightgray-bg-no-margin">
	<div class="container">
		<div class="row text-center">
			<div class="col-sm-4">
	          <span class="fa-stack fa-3x">
	          	<i class="fa fa-circle fa-stack-2x"></i>
	          	<strong class="fa-stack-1x  text-white">1</strong>
	          </span>
	          <p>Indiquez nous votre besoin particulier au travers de  notre formulaire ci dessous. ou appelez nous au 694840049</p>
			</div><!-- /.col-sm-4 -->

			<hr class="visible-xs">

			<div class="col-sm-4">
	          <span class="fa-stack fa-3x">
	          	<i class="fa fa-circle fa-stack-2x"></i>
	          	<strong class="fa-stack-1x  text-white">2</strong>
	          </span>
	          <p>Nous vous rappelerons au plus tot(generalement sous 24h) afin de comfirmer votre besoin et vous faire des propositions.</p>
			</div>

			<hr class="visible-xs">

			<div class="col-sm-4">
	          <span class="fa-stack fa-3x">
	          	<i class="fa fa-circle fa-stack-2x"></i>
	          	<strong class="fa-stack-1x  text-white">3</strong>
	          </span>
	          <p>Une fois que vous etes satisfait par l'un des profils proposes, nous mettons a votre disposition votre employe dans de bref delais.</p>
			</div>
		</div>
	</div>
</section>
<!-- End page header -->



<section id="top" class="contain clearfix">
	<div class="container">
		<div class="row">
			<br>
			<br>
			<div class="well col-lg-8 col-lg-offset-2">


				<h4 class="heading"><span>Decrivez votre offre d'emplois</span><span class="left"></span></h4>

				<%= form_for @job do |f| -%>
				  <fieldset>
				  	  <legend>Vos Informations Personelles</legend>
				  	  <div class="form-group">
					  	<%= f.label :nom, "Nom Complet" %>
					  	<%= f.text_field :nom,  required: 'required', class: "form-control" %>
					  </div>

					  <div class="form-group">
					  	<div class="row">
					  		<div class="col-sm-6">
					  			<%= f.label :telephone, "Telephone" %>
					  			<%= f.telephone_field :telephone, class: "form-control" ,  required: 'required' %>
					  		</div>
					  		<div class="col-sm-6">
					  			<%= f.label :email, "Email" %>
					  			<%= f.email_field :email, class: "form-control" %>
					  		</div>
					  	</div>
					  </div>
				  </fieldset>
				  <br><br>
				  <fieldset>
				  	  <legend>Details de l'offre</legend>
					  <div class="form-group">
					  	<%= f.label :title, "Titre" %>
					  	<%= f.text_field :title, class: "form-control",  required: 'required' %>
					  </div>
					  <div class="form-group">
					  	<%= f.label :description, "Description" %>
					  	<%= f.text_area :description,  rows: 6, class: "form-control" %>
					  </div>

					  <div class="form-group">
					  	<div class="row">
					  		<div class="col-sm-6">
					  			<%= f.label :ville, "Ville" %>
					  			<!-- <%= f.text_field :ville, class: "form-control" %> -->
							  	<%= f.select :ville, JobProposition.ville, {}, {class: "form-control" } %>
					  		</div>
					  		<div class="col-sm-6">
					  			<%= f.label :quartier, "Quartier" %>
					  			<%= f.text_field :quartier, class: "form-control",  required: 'required' %>
					  		</div>
					  	</div>
					  </div>

					  <div class="form-group">
					  	<div class="row">
					  		<div class="col-sm-6">
					  			<%= f.label :duree_contrat, "Type de Job" %>
					  			<!-- <%= f.text_field :duree_contrat, class: "form-control" %> -->
					  			<%= f.select :duree_contrat, JobProposition.type, {}, {class: "form-control" } %>

					  		</div>
					  		<div class="col-sm-6">
					  			<%= f.label :salaire, "Salaire" %>
								<!-- 	<%= f.text_field :salaire, class: "form-control" %> -->
					  			<%= f.select :salaire, JobProposition.salary, {}, {class: "form-control" } %>

					  		</div>
					  	</div>
					  </div>

					  <div class="form-group">
					  	<%= f.label :principale_taches, "Taches" %>
					  	<%= f.text_area :principale_taches, class: "form-control", rows: 3,  required: 'required' %>
					  </div>
					  <div class="form-group">
					  	<%= f.label :jour_travail, "Jour de travail" %>
						<!--   	<%= f.text_field :jour_travail, class: "form-control" %> -->
					  	<%= f.select :jour_travail, JobProposition.jour, {}, {class: "form-control" } %>
					  </div>

					  <div class="form-group">
					  	<div class="row">
						  	<div class="col-lg-12">
						  		<%= f.label :heure_travail_debut, "Horaire de travail" %>
						  	</div>
						  	<div class="col-lg-5 ">
						  		<div class="input-group">
								  	<input value="08:00" class="form-control" data-datetimepicker="true" data-options="{"showTodayButton":true,"format":"HH:mm"}" size="22" name="job_proposition[heure_travail_debut]" id="job_proposition_heure_travail_debut" type="text">
								  	<label class="input-group-addon" for="job_proposition_heure_travail_debut"><i class="fa fa-fw fa-calendar">
								  	</i></label>
						  		</div>
						  	</div>
						  	<div class="col-lg-2 text-center">
						  		 - 
						  	</div>
						  	<div class="col-lg-5">
						  		<div class="input-group">
								  	<input value="18:00" class="form-control" data-datetimepicker="true" data-options="{"showTodayButton":true,"format":"HH:mm"}" size="22" name="job_proposition[heure_travail_fin]" id="job_proposition_heure_travail_fin" type="text">
								  	<label class="input-group-addon" for="job_proposition_heure_travail_fin"><i class="fa fa-fw fa-calendar">
								  	</i></label>
							  	</div>
						  	</div>
					  	</div>
					  </div>

					  <div class="form-group">
					  	<%= f.label :status_emmenagement, "Desirer vous heberger votre employe chez vous?" %>
					  	<%= f.check_box :status_emmenagement %>
					  </div>
				  </fieldset>
					  <br>
					  <div class="clearfix"></div>

					  <%= f.submit "Sauvegarder", :disable_with => 'En cours...', class: 'btn btn-red btn-lg' %>

				<% end -%>
				
			</div>
		</div>
	</div>
</section>

<script type="text/javascript">
	$(function  () {
		$("#job_proposition_heure_travail_fin").datetimepicker({});
	});
</script>

app/views/job_propositions/show.html.erb
<h1>JobPropositions#show</h1>
<p>Find me in app/views/job_propositions/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='fr'>
<head>
  <title>NaNNYa - Trouvez des Menageres et Babysitters pres de chez vous</title>
  <meta name="description" content=  "<%= @meta_description  %>" />
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="msvalidate.01" content="D9757D91BD01A7B54251144574499A67" />
  <link rel="shortcut icon" type="image/x-icon" href="<%= asset_path 'favicon.ico' %>">
	<!--   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
 <!--  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <link href='https://fonts.googleapis.com/css?family=Monda:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render :partial => "shared/navigation" %>

	<% if notice || alert %>
	 <p class="alert alert-info"><%= notice %></p>
	 <p class="alert alert-warning"><%= alert %></p>
	<% end -%>
	<%= yield %>

	<%= render :partial => "shared/footer" %>
 
</body>
</html>

app/views/pages/contact.html.erb

<!-- Start page header -->
	<section id="page-head">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">		
					<h2>Nous Contacter</h2>
					<p>
					Nous serons plus que ravis de repondre a toute vos preocupations alors n'hesitez pas a nous laisser un message. nous reviendrons vers vous au plus vite. 
					<!-- Vous desirez
					 <button type="button" class="btn btn-dark btn-lg">Recruter</button> ou 
					 
					 <%= link_to "Vous enregistrer comme candidat", new_candidate_request_path, class: 'btn btn-dark btn-lg ' %> -->
					</p>
				</div>
			</div>
		</div>	
	</section>
	<!-- End page header -->
	
	<!-- Start contain -->
	<section id="top" class="contain clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">	
						<h4 class="heading"><span>Ecrivez Nous</span><span class="left"></span></h4>
						<form id="contactform" >
													
							<ul class="listForm">
								<li>
									<label>Votre Nom<span>&#40; Requis &#41;</span></label>
									<input class="form-control" type="text" name="name" required placeholder="Ex: Bryce Jobs" />									
									<div class="validation"></div>
								</li>
								<li>
									<label>Votre email<span>&#40; Requis &#41;</span></label>
									<input class="form-control" type="email" name="email" required placeholder="Ex: handler@yourdomain.com" />										
									<div class="validation"></div>
								</li>
								<li>
									<label>Sujet</label>
									<input class="form-control" type="text" name="suject" required placeholder="Ex: Besoin d'orientation" />									
									<div class="validation"></div>
								</li>
								<li>
									<label>Message<span>&#40; Requis &#41;</span></label>
									<textarea class="form-control" rows="9" name="message" required placeholder="Laissez nous un message"></textarea>												
									<div class="validation"></div>
								</li>
								<li>
									<input type="submit" value="Envoyer message" class="btn btn-lg btn-red" name="Submit" />
								</li>
							</ul>
						</form>
				</div>
				<div class="col-lg-4">
					<div class="contact-box">
						<p>
						<label>Address :</label>
						Derriere Pharmacie Blue, Hopital General, Yde
						</p>
						<p>
						<label>Phone :</label>
						683-867-665 ou 694-840-049
						</p>	
						<p>
						<label>Email :</label>
						lecebri@gmail.com ou  inbox@nannya.com 
						</p>						
					</div>
				</div>
			</div>		
		</div>
	</section>
	<!-- End contain -->


	 <section id="bottom">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 aligncenter">
						<h4>Vous avez en nous un partenaire de confiance</h4>
						<p>
						Nous saurons vous fournir le profil que vous recherchez dans de bref delais alors... 
						</p>	
						<p><a href="#" class="btn btn-lg btn-red">Exprimer votre Besoin</a><p>
					</div>
				</div>
			</div>				
		</section>

app/views/requete_candidats/confirm.html.erb
<section id="page-head">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">		
				<h2>Rejoignez Nous</h2>
				<p>
				Nous sommes perpetuellement a la recherche de femmes(filles) dynamique dans l'optique d'agrandir notre reseaux. Alors nous sommes honores que vous souhaitiez devenir membre de notre grande famille, Merci nous reviendrons vers vous.
				</p>
			</div>
		</div>
	</div>	
</section>

<br>
<br>

<div class="container">
	<div class="row">
		<div class="alert alert-success">
			<strong>Enregistrement Recu</strong><br />
			Merci pour votre interet, nous avons bien recu votre demande et nous vous rappellerons au plus tot. En esperant vous avoir avec nous bientot, Merci de continuer a nous faire confiance.
		</div>	
	</div>
</div>

<br>
<br>

<div class="container">
	<div class="row text-center">
		<div class="btn btn-lg btn-dark ">Voir la liste de job</div> ou
		<%= link_to "Retourner a l'accueil", root_path, class: "btn btn-lg btn-dark" %>
	</div>
</div>

<br>
<br>

app/views/requete_generales/confirm.html.erb
<!-- Start page header -->
	<section id="page-head">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">		
					<h2>Nous Contacter</h2>
					<p>
					Nous serons plus que ravis de repondre a toute vos preocupations alors n'hesitez pas a nous laisser un message. nous reviendrons vers vous au plus vite. 
					<!-- Vous desirez
					 <button type="button" class="btn btn-dark btn-lg">Recruter</button> ou 
					 
					 <%= link_to "Vous enregistrer comme candidat", new_candidate_request_path, class: 'btn btn-dark btn-lg ' %> -->
					</p>
				</div>
			</div>
		</div>	
	</section>
	<!-- End page header -->
	
	<!-- Start contain -->
	<section id="top" class="contain clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">	
					<br>
					<br>

							<div class="alert alert-success">
								<strong>Message Envoye</strong><br />
								Merci pour votre interet, nous avons bien recu votre demande et nous vous rappellerons au plus tot. En esperant vous avoir avec nous bientot, Merci de continuer a nous faire confiance.
							</div>	
						
					<br>
					<br>

					
						<div class=" text-center">
							<div class="btn btn-lg btn-dark ">Voir la liste de job</div> ou
							<%= link_to "Retourner a l'accueil", root_path, class: "btn btn-lg btn-dark" %>
						</div>
					
					<br>
					<br>
				</div>

				<div class="col-lg-4">
					<div class="contact-box">
						<p>
						<label>Address :</label>
						Derriere Pharmacie Blue, Hopital General, Yde
						</p>
						<p>
						<label>Phone :</label>
						683-867-665 ou 694-840-049
						</p>	
						<p>
						<label>Email :</label>
						lecebri@gmail.com ou  inbox@nannya.com 
						</p>						
					</div>
				</div>
			</div>		
		</div>
	</section>
	<!-- End contain -->


	 <section id="bottom">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 aligncenter">
						<h4>Vous avez en nous un partenaire de confiance</h4>
						<p>
						Nous saurons vous fournir le profil que vous recherchez dans de bref delais alors... 
						</p>	
						<p><a href="#" class="btn btn-lg btn-red">Exprimer votre Besoin</a><p>
					</div>
				</div>
			</div>				
		</section>

app/views/shared/_navigation.html.erb
	<header>
		<div class="navbar navbar-fixed-top">
			<div class="container">
				
				<%= link_to root_path, class: "navbar-brand hidden-xs hidden-sm" do  %>
					<img src="<%= asset_path 'nannya-logo.png' %>" alt="logo nannya agency" />
				<% end %>
				<img src="<%= asset_path 'nannya-logo.png' %>" alt="logo nannya agency" class="navbar-brand visible-sm visible-xs" />
				
				<a href="tel:+237694840049" class="call-btn visible-xs pull-right "><i class="fa fa-phone text-white"></i>694-840-049</a>

				<div class="nav-collapse  navbar-responsive-collapse">
					<ul class="nav navbar-nav">
						<li class="<%= active_class root_path %>">
							<%= link_to "Accueil", root_path %>				
						</li>
						<li class="<%= active_class offers_path  %>"><%= link_to "Derniere Offres", offers_path %></li>
						<li class="<%= active_class contact_path %>"><%= link_to "Contact", contact_path %>	</li>
						
						
					</ul>
				</div><!-- End nav-collapse -->
	
				<div class="navbar-right">
					
						<p class="contact-top hidden-xs hidden-sm">  Appeler : 694-840-049 ou </p>
						<%= link_to raw("<strong>Je suis Employeur </strong>"), new_job_proposition_path,
						 class: "btn btn-red navbar-btn hidden-xs"  %>
						<p class="contact-top hidden-xs hidden-sm">|</p>
						<%= link_to raw("<strong>Je suis Candidat </strong>"),	 new_candidate_request_path,
						 class: "btn btn-red navbar-btn hidden-xs" %>

				</div>
			</div><!-- End container -->
		</div><!-- End navbar -->
	</header>
	<!-- End header -->